# Generated by Django 3.2.24 on 2024-02-24 19:57

from django.db import migrations, models
import uploadFileApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=uploadFileApp.models.user_directory_path)),
            ],
        ),
    ]
